### PR TITLE
CI Setup with GitHub Actions

### PR DESCRIPTION
**Pull request by GrantBirki**
# CI Setup with GitHub Actions

👋 Hey! It's me again. I have a fork of your project and it is absolutely wired up with all sorts of CI jobs to help automate my version of your project. My fork comes baked with CI that ranges from linting, astro checks, JSON validation, to `.deploy` IssueOps commands that deploy my website to production via GitHub Actions and GitHub pages.

I wanted to help contribute and start by adding a few of the features I setup.

Here is a quick list of what the pull request does:

- Adds a basic `ci` job that runs `astro check` and `build` against the code base to ensure changes are valid
- Adds npm packages for `astro check` and also the types package for `js-yaml`
- Commits the `package-lock.json` file to version control so that CI can actually run (this is 100% needed)
- Adds a CI job to globally validate JSON / yaml files throughout the repo to ensure they syntactically correct
- Adds a `.node-version` file for those of us that use **nodenv**
- Adds a basic dependabot config to help with dependency management

As a bonus, here is what the Action's CI output looks like for your fancy new `ci` job that runs `astro check` and `build` 😉  

Screenshot 2023-09-21 at 11 25 25 PM

I plan on contributing to this project a lot more, this is just the start!

### CODE REVIEW

**Comment by GrantBirki** [comment]
@prototypa, let me know if you have any questions about these changes :bow:

**Comment by prototypa** [comment]
Hi @GrantBirki 

Thank you for this. Later I will review the details and let you know.

**Comment by GrantBirki** [comment]
@prototypa any feedback or questions that you may have?

**Comment by GrantBirki** [comment]
@prototypa or @widgeter, any feedback or suggestions on this? I can break this apart into multiple PRs if need be. I feel bad that the PR diff looks massive because I committed the `package-lock.json` file (even though its pretty much required for nearly all cases where CI is present)

**Comment by GrantBirki** [comment]
@davidawad thank you! Really hoping to get this merged so that others can use this as well. I haven't heard from the maintainers in a couple of months though so I hope they are doing okay!

**Comment by GrantBirki** [comment]
@prototypa or @widgeter, I'm going to go ahead and close this pull request if it does't receive any activity in the next week or I'm told otherwise.

**Comment by emelleby** [comment]
> @prototypa or @widgeter, I'm going to go ahead and close this pull request if it does't receive any activity in the next week or I'm told otherwise.

That would be a pity. Seems like this will improve the code base...

**Pull request closed without merging**
