### PR TITLE
adds View Transitions

### PR DESCRIPTION
**Pull request by diomed**

### CODE REVIEW

**Comment by iam-joel** [comment]
To complete ViewTransitions integration to this template need to add to the:

1. Layout.astro

  
```
<head>
    <CommonMeta />
    <Favicons />
    <CustomStyles />
    <ApplyColorMode />
    <Metadata {...metadata} />
    <SiteVerification />
    <Analytics />
    <ViewTransitions/>
 </head>
```
 
2. Header.astro for the nav bar to work well when theme changes
```
<header
  class:list={[
    { sticky: isSticky, relative: !isSticky, dark: isDark },
    "top-0 z-40 flex-none mx-auto w-full border-b border-gray-50/0 transition-[opacity] ease-in-out",
  ]}
  {...id ? { id } : {}}
  transition:persist
>
```

I've found an issue tho:
1. The Social Share button click does not work when ViewTransitions is being used. It works if you reload the single post but if you navigate to other pages and come back to the single post it won't work.

**Comment by diomed** [comment]
@prototypa what to do with this? I basically did everything, it's just that 2nd part is in another PR

**Comment by betarepos** [comment]
Should we make that optional or configurable? Browser support isnt that great at the moment with only Chromium supporting it

**Comment by diomed** [comment]
> Should we make that optional or configurable? Browser support isnt that great at the moment with only Chromium supporting it

about 77% of world population uses Chromium based browsers and for other people it will just fall back to regular, so I dont see the problem.

**Comment by betarepos** [comment]
more like	65.47% and yes falling back to regular should be the case, but watching the latest videos on it, there are side effects like breaking links for safari users. I mean im not arguing against viewtransition, just not implement it as default but as an option

**Comment by bencipher** [comment]
1. Hello guys, after seeing this issue I went through the ViewTransition library and I find it to be really cool, but I didn't really see it in action in the current demo app for this project running on vercel. I tried navigating the blog and I essentially search the codebase and I didn't see where it was initialised. Is it a WIP?

2. Also, I tried to add a serverless function so I can run the sendgrid api on a website I built using this theme however, I always get serverless function invocation failure:

```

Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: ENOENT: no such file or directory, open 'src/config.yaml'","reason":{"errorType":"Error","errorMessage":"ENOENT: no such file or directory, open 'src/config.yaml'","code":"ENOENT","errno":-2,"syscall":"open","path":"src/config.yaml","stack":["Error: ENOENT: no such file or directory, open 'src/config.yaml'","    at Object.openSync (node:fs:603:3)","    at Object.readFileSync (node:fs:471:35)","    at file:///var/task/vercel/path0/dist/chunks/pages/404.astro.6270e550.mjs:8:29","    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: ENOENT: no such file or directory, open 'src/config.yaml'","    at process.<anonymous> (file:///var/runtime/index.mjs:1250:17)","    at process.emit (node:events:526:35)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
Unknown application error occurred
Runtime.Unknown
```

How to replicate this:  

3.  From d36f60218b5d58c8478c8d10ac2a949afd14af7b add a vercel adapter, put it on SSR mode, then deploy. 

I read somewhere that the issue migh be coming from some libraries, which led me to be more curious, why is astro and other major libraries devDependencies in this project? I am coming from a Python background.

Thanks.

**Comment by diomed** [comment]
@bencipher this is not an issue.
you are in pull requests section, and I'm trying to get that integrated with my request.

**Comment by bencipher** [comment]
Oh my bad, sorry. I will raise it in the appropriate place.

**Comment by diomed** [comment]
> Oh my bad, sorry. I will create an issue now.
> 
> @diomed do you have an answer for the number one point as it relates to your PR

you will literally see it if PR gets accepted. 
that's the way it goes.

**Comment by bencipher** [comment]
Okay

**Comment by prototypa** [comment]
Hi @diomed 

Thanks for the PR and sorry for the delay in the respond. I have approved some other PRs you have done for AstroWind but this one requires thought.

I had already enabled ViewTransition since it was released in Astro and reverted it after doing some deep revisions. It created more problems than benefits.

Issues:
- Performance (page speed) is somewhat affected.
- Problems are often encountered in some browsers (as @betarepos mentioned)
- There are usually parts of AstroWind that stop working (as @iam-joel mentioned. There are more). This point is easily fixed with the events https://docs.astro.build/en/guides/view-transitions/#astropage-load and https://docs.astro.build/en/guides/view-transitions/#astroafter-swap
- Visually, its default behavior does not seem very pleasant to me, unless animations between pages are customized by hand.

On the other hand, it is very easy for each developer to activate ViewTransitions, once they download the template. So for now it didn't seem like a priority.

Soon I will add a PR with a refactoring of that little vanilla script that is used for the few client-side interactions in the template and I will do a detailed review of the ViewTransitions issue in AstroWind so that nothing fails. So I think it's convenient to wait.

**Comment by prototypa** [comment]
I'm closing this PR temporarily until the aforementioned issues with `ViewTransitions` have been resolved.

**Pull request closed without merging**
