### PR TITLE
Add I18N Support

### PR DESCRIPTION
**Pull request by reuseman**
As previously discussed in issue #219, this proposal outlines the implementation of I18N (Internationalization) support using the library available at https://github.com/jlarmstrongiv/astro-i18n-aut.

The key features introduced by this proposal include:

- A language picker to facilitate the selection of the appropriate language.
- Translation strings that are automatically derived from the content and stored in the src/i18n folder.
- A showcase of I18N in action through the index.astro page, available in both English and Italian.
- Similarly, a bilingual blog is a demonstration of the I18N capabilities.

The library functions by generating pages for different locales during the `npm run build` phase. For instance, given a dynamic route like `/astrowind-template-in-depth/index.html`, and with enabled locales such as `[en-US, it-IT]`, it creates the following pages:
- /astrowind-template-in-depth/index.html
- /it/astrowind-template-in-depth/index.html
- /en/astrowind-template-in-depth/index.html

However, during development using `npm run dev`, frequent language switches between pages may lead to unavailable pages, but that's expected since the `getStaticPaths()` function can only be called once within Astro's constraints.

While I've made progress in making everything functional, some aspects remain unfinished. To ensure a smoother workflow and to enable @prototypa to review the work, I've initiated this pull request. This approach becomes more viable as the main branch has seen significant activity recently, including various content edits that could complicate merging.

The pending tasks include:
- Ensure that links throughout the entire website accurately reflect the selected language.
- Confirming seamless functionality regardless of whether the trailing slash is enabled or disabled (for more details, refer to https://github.com/jlarmstrongiv/astro-i18n-aut#astro-config-options).

### CODE REVIEW

**Comment by prototypa** [comment]
Awesome @reuseman 

Just had a quick look at all the PR, lots of work. I liked how you managed to get the posts translated. At that point I was stuck.

Tonight I will be doing a deep review and I will write to you.

Thank you so much.
See you soon.

**Comment by reuseman** [comment]
Hi @prototypa,

Thank you for your kind words and for taking the time to review the PR. I'm glad you liked the progress so far. Looking forward to your deep review. Feel free to reach out if you have any questions or suggestions. Let me know if there is something I can help you with. Waiting for your feedback.

**Comment by prototypa** [comment]
Hi @reuseman 

I was reviewing your PR in detail. I really like what you have done and I have in mind some ideas that could be changed in **AstroWind** to publish it without _i18n_ and make it easy to activate it. These ideas are mixed with other things that are being done in **AstroWind** for version _v2_ and still needs some work.

I have a proposal to start. I just created a branch named [i18n](https://github.com/onwidget/astrowind/tree/i18n). What if we do the following:

- You send your PR to this i18n branch.
- We approve your PR. That branch would have all that good work that you have developed.
- Then, the [README](https://github.com/onwidget/astrowind/blob/main/README.md) is modified and a clear reference to I18N support is added which can be found there.

Then it would be time to continue brainstorming and always keep the two branches synchronized, a task that I will do.

What do you think? If you have any other suggestions, please let me know.

**Comment by reuseman** [comment]
Sure, that sounds like a well-considered plan. How are you envisioning the implementation of i18n in the optional feature? One approach I thought about is to introduce an option within the settings for the blog. This option could enable i18n support and consequently display only a single translated page (for instance, landing with i18n support), as an illustrative example, within the landing/homes sections, alongside the blog.

Regarding the merging aspect, that's perfectly fine. If we're aligned with the ultimate goal, I'm more than willing to assist you with the necessary support. The current state of the website's main content is indeed quite messy due to numerous conflicts. Anyhow, please inform me about where I can offer my assistance if needed

**Pull request merged**
