### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by phanect**
This PR adds configs for GitHub Actions.
Currently, it verifies if the build and check (with `@astro/check`, ESLint, and Prettier) are successfully done.
I also fixed errors and warnings by the linters.

- Currently, GitHub Actions runs with Node.js v18, v20, and v22. I found AstroWind also supports v21 according to `engine.node` in package.json, and should we test with v21 on the CI?
- If the naming for npm scripts does not match your preference, let me know how I should fix it, or feel free to add commits to fix it.
- This PR includes changes for package-lock.json. Since it would probably conflict with #501, please regenerate package-lock.json on your end, or let me regenerate it if it is required.
- You might want to overwrite package-lock.json on your end to ensure I'm not an attacker to inject malicious code in package-lock.json

### CODE REVIEW

**Comment by phanect** [comment]
I have rebased this branch to resolve the conflict.

**Comment by prototypa** [comment]
Hi @phanect 

Thank you very much for this. 

Question: why do you repeat the `check` job with version `22` if you have already executed that verification in the `build` job?

**Comment by phanect** [comment]
Thank you for the review, @prototypa.

I I guess `astro build` does not check everything checked by `astro check`. It seems to run only some checks.

I will check the behavior of `astro build` and `astro check` again.

**Comment by phanect** [comment]
@prototypa I have confirmed that `astro build` does not check the typing error of TypeScript while `astro check` does.
Therefore, both `astro build` and `astro check` should run on the CI, IMO.

astro build returns 0 on the shell while astro check returns 1 because there is unmatched error in the TypeScript code

**Comment by phanect** [comment]
No, sorry, I have misunderstood what you mean.
I just noticed I wrote `npm run check` both in the `build` and `check` **jobs** of the GitHub Actions configs.
That's just a mistake. I will fix it.

**Comment by prototypa** [comment]
Hi @phanect 

Thank you so much! Let's approve this PR.

**Pull request merged**
