### PR TITLE
Eslint corrections

### PR DESCRIPTION
**Pull request by ShoGinn**
Here is my contribution to my issue #428

### CODE REVIEW

**Comment by ShoGinn** [comment]
I noticed that this has many fixes (per the prettier formatting that VS Code formatted on save) that make auditing difficult, so I apologize for that!

**Comment by JuliusBairaktaris** [comment]
LGTM, except for 55e50e8faa68d5745e3666c257b23e4a2b89cc65 as astroEslintParser is used to target .astro files. I would recommend removing the commit.

**Comment by ShoGinn** [comment]
@JuliusBairaktaris that just is for the folder not `**/*.astro`

**Comment by JuliusBairaktaris** [comment]
I was unaware of this behavior. Thanks for the explanation!

**Comment by prototypa** [comment]
Hi @ShoGinn and @JuliusBairaktaris 

Thank you for this.

**Pull request merged**
